[package]
name = "wikirs"
version = "0.1.28-dev"
authors = ["chris west <c@xvxx.io>"]
edition = "2018"
license = "MIT"
description = "dead simple personal wiki"
repository = "https://github.com/yonasBSD/wiki.rs"
readme = "README.md"
keywords = ["wiki", "markdown", "cli"]
categories = ["command-line-utilities"]
exclude = [
  "wiki/*",
]

[[bin]]
name = "wikirs"
path = "src/main.rs"

[features]
default = []

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="\\d+\\.\\d+\\.\\d+-dev", replace="{{version}}"},
]
dev-version-ext = "dev"

[build-dependencies]
vial = "0.1.9"

[dependencies]
hatter = { git = "https://github.com/tdryer/hatter", branch = "scope-fix" }
vial = { version = "0.1.8", features = ["cookies"] }

pulldown-cmark = { version = "0.7", default-features = false }
linkify = "0.4.0"
